<x-layouts.app title="Formular-Einreichungen">
    @php($statusLabels = ['submitted'=>'Eingereicht','in_review'=>'In Bearbeitung','approved'=>'Genehmigt','rejected'=>'Abgelehnt','completed'=>'Abgeschlossen'])
    <div class="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><a href="{{ route('forms.index') }}" class="text-sm font-semibold text-blue-700 hover:underline">← Formulare</a><h1 class="mt-2 text-3xl font-bold tracking-tight">Einreichungen</h1><p class="mt-2 text-sm text-slate-500">Zentraler Posteingang für öffentliche und interne Formulare.</p></div></div>
    @if(session('success'))<div class="mt-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('success') }}</div>@endif

    <section class="cv-panel mt-6 overflow-hidden">
        <div class="border-b border-slate-200 p-5"><form method="get" class="grid gap-3 lg:grid-cols-[1fr_240px_200px_auto]"><input class="cv-input" name="q" value="{{ request('q') }}" placeholder="Vorgangsnummer, Name oder E-Mail …"><select class="cv-input" name="form_id"><option value="">Alle Formulare</option>@foreach($forms as $form)<option value="{{ $form->id }}" @selected((string)request('form_id')===(string)$form->id)>{{ $form->name }}</option>@endforeach</select><select class="cv-input" name="status"><option value="">Alle Status</option>@foreach($statusLabels as $status=>$label)<option value="{{ $status }}" @selected(request('status')===$status)>{{ $label }}</option>@endforeach</select><button class="cv-button border border-slate-300 bg-white">Filtern</button></form></div>
        <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Vorgang</th><th class="px-5 py-3">Formular</th><th class="px-5 py-3">Einreicher</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Aktueller Schritt</th><th class="px-5 py-3">Eingang</th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($submissions as $submission)<tr class="hover:bg-slate-50"><td class="px-5 py-3"><a href="{{ route('forms.submissions.show', $submission) }}" class="font-bold text-blue-700 hover:underline">{{ $submission->reference_number }}</a></td><td class="px-5 py-3"><span class="font-semibold">{{ $submission->form?->name }}</span><br><span class="text-xs text-slate-500">{{ $submission->form?->form_type === 'public' ? 'Öffentlich' : 'Intern' }}</span></td><td class="px-5 py-3">{{ $submission->member?->person?->display_name ?: ($submission->submitter_name ?: 'Anonym') }}@if($submission->submitter_email)<br><span class="text-xs text-slate-500">{{ $submission->submitter_email }}</span>@endif</td><td class="px-5 py-3"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{{ $statusLabels[$submission->status] ?? $submission->status }}</span></td><td class="px-5 py-3">{{ $submission->currentStep?->workflowStep?->name ?: '–' }}@if($submission->currentStep?->due_at)<br><span class="text-xs {{ $submission->currentStep->due_at->isPast() ? 'font-semibold text-red-700' : 'text-slate-500' }}">Frist {{ $submission->currentStep->due_at->format('d.m.Y') }}</span>@endif</td><td class="whitespace-nowrap px-5 py-3">{{ $submission->submitted_at?->format('d.m.Y H:i') }}</td></tr>
            @empty<tr><td colspan="6" class="px-5 py-10 text-center text-slate-500">Keine Einreichungen für den gewählten Filter.</td></tr>@endforelse
        </tbody></table></div>
        <div class="border-t border-slate-200 p-4">{{ $submissions->links() }}</div>
    </section>
</x-layouts.app>
