<x-layouts.app title="Übersicht">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div><h1 class="text-2xl font-bold tracking-tight sm:text-3xl">Guten Morgen, {{ auth()->user()->person?->first_name ?? 'Willkommen' }}</h1><p class="mt-1 text-sm text-slate-500">Hier ist die aktuelle Übersicht für {{ auth()->user()->currentTenant->name }}.</p></div>
    </div>
    <div class="mt-6 grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]">
        <section class="cv-panel p-5" aria-labelledby="entwicklung"><div class="flex items-center justify-between"><h2 id="entwicklung" class="font-bold">Mitgliederentwicklung</h2><span class="text-xs text-slate-500">Noch keine Mitgliederdaten</span></div><div class="mt-8 flex min-h-48 items-center justify-center rounded-lg border border-dashed border-slate-300 bg-slate-50 px-6 text-center"><div><div class="mx-auto grid h-12 w-12 place-items-center rounded-full bg-blue-100 text-2xl text-blue-700">↗</div><p class="mt-3 font-semibold">Noch keine Auswertung verfügbar</p><p class="mt-1 max-w-sm text-sm text-slate-500">Sobald Mitgliedschaften erfasst sind, erscheinen hier Entwicklung und Statusgruppen.</p></div></div></section>
        <section class="cv-panel p-5" aria-labelledby="organisation"><h2 id="organisation" class="font-bold">Organisation</h2><p class="mt-5 text-lg font-bold">{{ auth()->user()->currentTenant->name }}</p><p class="text-sm text-slate-500">Tarif {{ ucfirst(auth()->user()->currentTenant->plan) }}</p><dl class="mt-6 grid grid-cols-2 gap-y-4 text-sm"><dt class="text-slate-500">Status</dt><dd class="font-semibold text-emerald-700">{{ ucfirst(auth()->user()->currentTenant->status) }}</dd><dt class="text-slate-500">Mandant</dt><dd class="truncate font-mono text-xs">{{ auth()->user()->currentTenant->public_id }}</dd></dl></section>
    </div>
    <div class="mt-4 grid gap-4 lg:grid-cols-2">
        <section class="cv-panel p-5"><div class="flex justify-between"><h2 class="font-bold">Offene Vorgänge</h2><span class="text-sm text-slate-400">0</span></div><div class="mt-8 mb-4 text-center"><p class="font-semibold">Alles erledigt</p><p class="mt-1 text-sm text-slate-500">Derzeit warten keine Vorgänge auf Ihre Bearbeitung.</p></div></section>
        <section class="cv-panel p-5"><div class="flex justify-between"><h2 class="font-bold">Nächste Termine</h2><span class="text-sm text-slate-400">0</span></div><div class="mt-8 mb-4 text-center"><p class="font-semibold">Keine anstehenden Termine</p><p class="mt-1 text-sm text-slate-500">Hier stehen künftig die nächsten Sitzungen und Veranstaltungen.</p></div></section>
    </div>
    <section class="cv-panel mt-4 overflow-hidden" aria-labelledby="systemstatus"><div class="border-b border-slate-200 px-5 py-4"><h2 id="systemstatus" class="font-bold">Systemstatus</h2></div><div class="overflow-x-auto"><table class="w-full min-w-[640px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Bereich</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Stand</th></tr></thead><tbody class="divide-y divide-slate-100"><tr><td class="px-5 py-4 font-semibold">Mandantentrennung</td><td class="px-5 py-4"><span class="text-emerald-700">● Aktiv</span></td><td class="px-5 py-4 text-slate-500">Request-Kontext und automatische Scopes</td></tr><tr><td class="px-5 py-4 font-semibold">Organisationsbaum</td><td class="px-5 py-4"><span class="text-emerald-700">● Bereit</span></td><td class="px-5 py-4 text-slate-500">Closure Table, unbegrenzte Tiefe</td></tr><tr><td class="px-5 py-4 font-semibold">Fachmodule</td><td class="px-5 py-4"><span class="text-amber-700">● Geplant</span></td><td class="px-5 py-4 text-slate-500">Aktivierung je Entwicklungsphase</td></tr></tbody></table></div></section>
</x-layouts.app>
