<x-layouts.app title="Sammelbestätigungen">
    <div class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div><p class="text-sm font-semibold text-blue-700">Spenden · Zuwendungsbestätigungen</p><h1 class="text-2xl font-bold tracking-tight">Sammelbestätigungen</h1><p class="mt-1 max-w-3xl text-sm text-slate-500">Mehrere Zuwendungen derselben Person in einem Dokument zusammenfassen. Jede Einzelzuwendung wird Bestandteil der PDF-Anlage und bleibt revisionssicher nachvollziehbar.</p></div>
        <a href="{{ route('finance.recovery.index') }}" class="cv-button-secondary">Spenden & Erstattungen</a>
    </div>

    @if(session('success'))<div class="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <section class="cv-panel mt-5 p-5">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-lg font-bold">Ausstellungsjahr</h2><p class="text-sm text-slate-500">Es werden nur noch nicht einzeln oder gesammelt bescheinigte Zuwendungen angezeigt.</p></div><form method="get" class="flex items-end gap-2"><label><span class="cv-label">Jahr</span><input type="number" min="2000" max="2100" class="cv-input w-32" name="year" value="{{ $year }}"></label><button class="cv-button-secondary">Anzeigen</button></form></div>
    </section>

    <form method="post" action="{{ route('finance.donations.collective-certificates.issue') }}" class="cv-panel mt-5 overflow-hidden">@csrf
        <div class="flex flex-col gap-3 border-b border-slate-200 px-5 py-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-lg font-bold">Zuwendungen auswählen</h2><p class="text-sm text-slate-500">Mindestens zwei Positionen mit identischem Namen und identischer Anschrift. Die serverseitige Prüfung verhindert Mischungen unterschiedlicher Zuwendender.</p></div><button class="cv-button-primary">Sammelbestätigung ausstellen</button></div>
        <div class="overflow-x-auto"><table class="w-full min-w-[1050px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-4 py-3"><span class="sr-only">Auswahl</span></th><th class="px-4 py-3">Zuwendender</th><th class="px-4 py-3">Datum</th><th class="px-4 py-3">Art</th><th class="px-4 py-3">Zweck</th><th class="px-4 py-3 text-right">Betrag</th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($eligible as $donation)<tr><td class="px-4 py-3"><input type="checkbox" name="donations[]" value="{{ $donation->id }}" aria-label="{{ $donation->donation_number }} auswählen"></td><td class="px-4 py-3"><p class="font-semibold">{{ $donation->donor_name }}</p><p class="text-xs text-slate-500">{{ $donation->donor_street }}, {{ $donation->donor_postal_code }} {{ $donation->donor_city }}</p><p class="text-xs text-slate-400">{{ $donation->donation_number }}</p></td><td class="px-4 py-3">{{ $donation->donation_date->format('d.m.Y') }}</td><td class="px-4 py-3">{{ match($donation->donation_kind){'membership_contribution'=>'Mitgliedsbeitrag','expense_waiver'=>'Aufwandsverzicht',default=>'Geldzuwendung'} }}</td><td class="px-4 py-3">{{ $donation->purpose }}</td><td class="px-4 py-3 text-right font-bold">{{ number_format((float)$donation->amount,2,',','.') }} €</td></tr>@empty<tr><td colspan="6" class="px-5 py-10 text-center text-slate-500">Für {{ $year }} gibt es keine noch verfügbaren Zuwendungen für eine Sammelbestätigung.</td></tr>@endforelse
        </tbody></table></div>
        @if($eligible->isNotEmpty())<div class="border-t border-slate-200 bg-slate-50 px-5 py-3 text-xs text-slate-500">Auswahl und steuerliche Stammdaten werden beim Ausstellen erneut serverseitig geprüft. Eine Zuwendung kann nicht gleichzeitig Bestandteil einer gültigen Einzel- und Sammelbestätigung sein.</div>@endif
    </form>

    <section class="cv-panel mt-5 overflow-hidden">
        <div class="border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-bold">Ausgestellte Sammelbestätigungen</h2><p class="text-sm text-slate-500">Storno bleibt historisch erhalten; eine Korrektur wird anschließend mit neuer Dokumentnummer neu ausgestellt.</p></div>
        <div class="overflow-x-auto"><table class="w-full min-w-[1100px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-4 py-3">Dokument</th><th class="px-4 py-3">Zuwendender</th><th class="px-4 py-3">Zeitraum</th><th class="px-4 py-3 text-right">Positionen</th><th class="px-4 py-3 text-right">Gesamt</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Aktion</th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($certificates as $certificate)<tr class="align-top"><td class="px-4 py-3"><p class="font-semibold">{{ $certificate->certificate_number }}</p><p class="text-xs text-slate-500">{{ $certificate->issue_date->format('d.m.Y') }}</p></td><td class="px-4 py-3">{{ $certificate->donor_snapshot['name'] ?? '—' }}<p class="text-xs text-slate-500">{{ $certificate->donor_snapshot['street'] ?? '' }} {{ $certificate->donor_snapshot['postal_code'] ?? '' }} {{ $certificate->donor_snapshot['city'] ?? '' }}</p></td><td class="px-4 py-3">{{ $certificate->period_from->format('d.m.Y') }}–{{ $certificate->period_to->format('d.m.Y') }}</td><td class="px-4 py-3 text-right">{{ $certificate->items->count() }}</td><td class="px-4 py-3 text-right font-bold">{{ number_format((float)$certificate->total_amount,2,',','.') }} €</td><td class="px-4 py-3"><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $certificate->status==='issued'?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700' }}">{{ $certificate->status==='issued'?'Gültig':'Storniert' }}</span>@if($certificate->void_reason)<p class="mt-1 max-w-xs text-xs text-red-600">{{ $certificate->void_reason }}</p>@endif</td><td class="px-4 py-3"><div class="flex flex-wrap gap-3"><a class="text-xs font-bold text-blue-700" href="{{ route('finance.donation-collective-certificates.pdf',$certificate) }}">PDF</a>@if($certificate->status==='issued')<details><summary class="cursor-pointer text-xs font-bold text-red-700">Stornieren</summary><form method="post" action="{{ route('finance.donation-collective-certificates.void',$certificate) }}" class="mt-2 w-64 rounded-lg border border-red-100 bg-white p-3 shadow-lg">@csrf @method('patch')<label><span class="cv-label">Grund *</span><textarea required maxlength="500" class="cv-input min-h-20 py-2" name="reason"></textarea></label><button class="mt-2 text-xs font-bold text-red-700">Storno bestätigen</button></form></details>@endif</div></td></tr>@empty<tr><td colspan="7" class="px-5 py-10 text-center text-slate-500">Noch keine Sammelbestätigungen in {{ $year }}.</td></tr>@endforelse
        </tbody></table></div>
    </section>
</x-layouts.app>
