<!doctype html>
<html lang="de"><head><meta charset="utf-8"><style>
@page{margin:18mm 18mm 20mm}body{font-family:DejaVu Sans,sans-serif;color:#0f172a;font-size:10pt;line-height:1.45}h1{font-size:21pt;margin:0 0 4mm}.muted{color:#64748b}.top{display:table;width:100%;margin-bottom:16mm}.top>div{display:table-cell;vertical-align:top;width:50%}.right{text-align:right}.recipient{margin:0 0 14mm;width:80mm}.sender{font-size:7.5pt;color:#64748b;border-bottom:1px solid #cbd5e1;margin-bottom:2mm}.meta{width:100%;border-collapse:collapse;margin:5mm 0 8mm}.meta td{padding:1.3mm 0}.items{width:100%;border-collapse:collapse}.items th{background:#f1f5f9;text-align:left;padding:2.5mm;border-bottom:1px solid #cbd5e1}.items td{padding:2.5mm;border-bottom:1px solid #e2e8f0}.num{text-align:right}.totals{margin:6mm 0 0 auto;width:80mm;border-collapse:collapse}.totals td{padding:1.5mm}.total{font-weight:bold;font-size:12pt;border-top:2px solid #0f172a}.footer{position:fixed;bottom:-11mm;left:0;right:0;border-top:1px solid #cbd5e1;padding-top:2mm;font-size:7.5pt;color:#64748b}.notice{margin-top:9mm;padding:4mm;background:#f8fafc}
</style></head><body>
@php($recipient=$invoice->recipient_snapshot ?? [])
<div class="top"><div><strong>{{ $settings?->creditor_name ?: $tenant->name }}</strong><br>@if($settings?->street){{ $settings->street }}<br>@endif @if($settings?->postal_code || $settings?->city){{ $settings->postal_code }} {{ $settings->city }}<br>@endif @if($settings?->country){{ $settings->country }}@endif</div><div class="right"><h1>Rechnung</h1><strong>{{ $invoice->invoice_number }}</strong></div></div>
<div class="recipient"><div class="sender">{{ $settings?->creditor_name ?: $tenant->name }}@if($settings?->street) · {{ $settings->street }}@endif @if($settings?->postal_code || $settings?->city) · {{ $settings->postal_code }} {{ $settings->city }}@endif</div><strong>{{ $recipient['name'] ?? 'Rechnungsempfänger' }}</strong><br>@if(!empty($recipient['contact_name']) && ($recipient['contact_name'] !== ($recipient['name'] ?? null))){{ $recipient['contact_name'] }}<br>@endif @if(!empty($recipient['street'])){{ $recipient['street'] }}<br>@endif {{ $recipient['postal_code'] ?? '' }} {{ $recipient['city'] ?? '' }}<br>@if(!empty($recipient['country']) && $recipient['country'] !== 'DE'){{ $recipient['country'] }}@endif</div>
<table class="meta"><tr><td><span class="muted">Rechnungsdatum</span><br><strong>{{ $invoice->invoice_date?->format('d.m.Y') }}</strong></td><td><span class="muted">Fällig am</span><br><strong>{{ $invoice->due_date?->format('d.m.Y') }}</strong></td><td><span class="muted">Mitgliedsnummer</span><br><strong>{{ $recipient['member_number'] ?? '—' }}</strong></td></tr></table>
<table class="items"><thead><tr><th>Position</th><th class="num">Menge</th><th class="num">Einzelpreis</th><th class="num">MwSt.</th><th class="num">Gesamt</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $item->description }}</td><td class="num">{{ number_format((float)$item->quantity,2,',','.') }}</td><td class="num">{{ number_format((float)$item->unit_price,2,',','.') }} €</td><td class="num">{{ number_format((float)$item->tax_rate,2,',','.') }} %</td><td class="num">{{ number_format((float)$item->gross_amount,2,',','.') }} €</td></tr>@endforeach</tbody></table>
<table class="totals"><tr><td>Netto</td><td class="num">{{ number_format((float)$invoice->net_amount,2,',','.') }} €</td></tr>@if((float)$invoice->tax_amount !== 0.0)<tr><td>Steuer</td><td class="num">{{ number_format((float)$invoice->tax_amount,2,',','.') }} €</td></tr>@endif<tr class="total"><td>Gesamt</td><td class="num">{{ number_format((float)$invoice->gross_amount,2,',','.') }} €</td></tr>@if($invoice->credited_amount > 0)<tr><td>Gutschriften</td><td class="num">− {{ number_format($invoice->credited_amount,2,',','.') }} €</td></tr>@endif @if((float)$invoice->paid_amount > 0)<tr><td>Zahlungen</td><td class="num">− {{ number_format((float)$invoice->paid_amount,2,',','.') }} €</td></tr>@endif<tr><td><strong>Offen</strong></td><td class="num"><strong>{{ number_format($invoice->open_amount,2,',','.') }} €</strong></td></tr></table>
@if($invoice->open_amount > 0)<div class="notice">Bitte überweisen Sie den offenen Betrag bis zum <strong>{{ $invoice->due_date?->format('d.m.Y') }}</strong>@if($settings?->iban) auf das Konto {{ $settings->masked_iban }}@endif und geben Sie als Verwendungszweck <strong>{{ $invoice->invoice_number }}</strong> an.</div>@endif
@if($invoice->notes)<p><strong>Hinweis:</strong> {{ $invoice->notes }}</p>@endif
<div class="footer">{{ $settings?->creditor_name ?: $tenant->name }}@if($settings?->tax_number) · St.-Nr. {{ $settings->tax_number }}@endif @if($settings?->vat_id) · USt-IdNr. {{ $settings->vat_id }}@endif @if($settings?->invoice_footer)<br>{{ $settings->invoice_footer }}@endif</div>
</body></html>
